### ISSUE TITLE
Fails to compile on MacOS Monterey 12.6

### ISSUE THREAD

**Issue by neosquid** [z00m128/sjasmplus#247]
Hello,

I'm trying to compile latest Sjasmplus v1.20.3 which fails, with make clean, make, the following text is output in the terminal:

sjasm/lua_sjasm.cpp:35:10: fatal error: 'LuaBridge/LuaBridge.h' file not found
#include "LuaBridge/LuaBridge.h"
         ^~~~~~~~~~~~~~~~~~~~~~~

Thanks

**Comment by ped7g** [comment]
please follow https://github.com/z00m128/sjasmplus/blob/master/INSTALL.md#getting-full-source-code-of-sjasmplus

Look specifically for "submodules" hints. It's very likely you just didn't clone the submodules so LuaBridge sources are missing on your disk and it will hopefully compile correctly after submodules are initialized.

Reopen the bug if this doesn't help. :) Have a nice day.
